name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
    
    - name: Create application icon
      run: python create_icon.py
    
    - name: Build executable
      run: python build_exe.py
    
    - name: Install NSIS
      run: |
        choco install nsis -y
        refreshenv
    
    - name: Verify files exist
      run: |
        dir dist
        if (Test-Path "dist\DiscordTrayManager.exe") { 
          Write-Host "✓ Executable found" 
        } else { 
          Write-Host "✗ Executable not found" 
          exit 1 
        }
    
    - name: Copy files for installer
      run: |
        copy "dist\DiscordTrayManager.exe" .
        copy "config.json" .
        copy "README.md" .
    
    - name: Build installer
      run: |
        & "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi
    
    - name: Create portable archive
      run: |
        Compress-Archive -Path "Discord_Tray_Manager_Portable\*" -DestinationPath "Discord_Tray_Manager_Portable.zip"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Discord-Tray-Manager-Windows
        path: |
          Discord_Tray_Manager_Setup.exe
          Discord_Tray_Manager_Portable.zip
    
    - name: Release binaries
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Discord_Tray_Manager_Setup.exe
          Discord_Tray_Manager_Portable.zip 