name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow pystray
    
    - name: Create application icon
      run: python create_icon.py
    
    - name: Build executable
      run: python build_exe.py
    
    - name: Install NSIS
      run: |
        choco install nsis -y --force
        $env:PATH += ";C:\Program Files (x86)\NSIS"
        echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Verify NSIS installation
      run: |
        & "C:\Program Files (x86)\NSIS\makensis.exe" /VERSION
    
    - name: Verify files exist
      run: |
        dir dist
        if (Test-Path "dist\DiscordTrayManager.exe") { 
          Write-Host "Executable found" 
        } else { 
          Write-Host "Executable not found" 
          exit 1 
        }
    
    - name: Copy executable for installer
      run: |
        if (!(Test-Path "DiscordTrayManager.exe")) {
          copy "dist\DiscordTrayManager.exe" .
          Write-Host "Copied executable to root directory"
        } else {
          Write-Host "Executable already exists in root directory"
        }
    
    - name: Verify installer files
      run: |
        Write-Host "Files in root directory:"
        dir
        if (!(Test-Path "DiscordTrayManager.exe")) { 
          Write-Host "Missing DiscordTrayManager.exe"
          exit 1 
        }
        if (!(Test-Path "config.json")) { 
          Write-Host "Missing config.json"
          exit 1 
        }
        if (!(Test-Path "README.md")) { 
          Write-Host "Missing README.md"
          exit 1 
        }
        if (!(Test-Path "installer.nsi")) { 
          Write-Host "Missing installer.nsi"
          exit 1 
        }
    
    - name: Build installer
      run: |
        & "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi
    
    - name: Create portable archive
      run: |
        if (Test-Path "Discord_Tray_Manager_Portable") {
          Compress-Archive -Path "Discord_Tray_Manager_Portable\*" -DestinationPath "Discord_Tray_Manager_Portable.zip"
        } else {
          Write-Host "Portable directory not found"
          exit 1
        }
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Discord-Tray-Manager-Windows
        path: |
          Discord_Tray_Manager_Setup.exe
          Discord_Tray_Manager_Portable.zip
    
    - name: Release binaries
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Discord_Tray_Manager_Setup.exe
          Discord_Tray_Manager_Portable.zip 